-- Configuration
-- by: iElden
-- 18 DEC 2020

INSERT INTO Parameters(ParameterId, Name, Description, Domain, DefaultValue, ConfigurationGroup, ConfigurationId, GroupId, SortIndex) VALUES
    ('BBG_CFG_SHOW_ADVANCED', 'BBG_CFG_SHOW_ADVANCED_NAME', 'BBG_CFG_SHOW_ADVANCED_DESC', 'bool', 0, 'Game', 'BBG_CFG_SHOW_ADVANCED', 'AdvancedOptions', 4100),
    ('BBG_CFG_ENABLE_CITY_STATE_REWORK', 'BBG_CFG_ENABLE_CITY_STATE_REWORK_NAME', 'BBG_CFG_ENABLE_CITY_STATE_REWORK_DESC', 'bool', 1, 'Game', 'BBG_CFG_ENABLE_CITY_STATE_REWORK', 'AdvancedOptions', 4101),
    ('BBG_CFG_ENABLE_GREAT_PEOPLE_REWORK', 'BBG_CFG_ENABLE_GREAT_PEOPLE_REWORK_NAME', 'BBG_CFG_ENABLE_GREAT_PEOPLE_REWORK_DESC', 'bool', 1, 'Game', 'BBG_CFG_ENABLE_GREAT_PEOPLE_REWORK', 'AdvancedOptions', 4102),
    ('BBG_CFG_ALLOW_ANTI_AIR_SHOOT_AIRPLANE', 'BBG_CFG_ALLOW_ANTI_AIR_SHOOT_AIRPLANE_NAME', 'BBG_CFG_ALLOW_ANTI_AIR_SHOOT_AIRPLANE_DESC', 'bool', 0, 'Game', 'BBG_CFG_ALLOW_ANTI_AIR_SHOOT_AIRPLANE', 'AdvancedOptions', 4103);

INSERT INTO ParameterDependencies(ParameterId, ConfigurationGroup, ConfigurationId, ConfigurationValue) VALUES
    ('BBG_CFG_ENABLE_CITY_STATE_REWORK', 'Game', 'BBG_CFG_SHOW_ADVANCED', '1'),
    ('BBG_CFG_ENABLE_GREAT_PEOPLE_REWORK', 'Game', 'BBG_CFG_SHOW_ADVANCED', '1'),
    ('BBG_CFG_ALLOW_ANTI_AIR_SHOOT_AIRPLANE', 'Game', 'BBG_CFG_SHOW_ADVANCED', '1');