-- Created by iElden

UPDATE Modifiers SET SubjectRequirementSetId='BBG_PLAYER_HAS_MOBILISATION_REQUIREMENTS' WHERE ModifierId='TRAIT_LAND_CORPS_COMBAT_STRENGTH';
UPDATE Modifiers SET SubjectRequirementSetId='BBG_PLAYER_HAS_MOBILISATION_REQUIREMENTS' WHERE ModifierId='TRAIT_LAND_ARMIES_COMBAT_STRENGTH';

INSERT OR IGNORE INTO RequirementSets(RequirementSetId , RequirementSetType) VALUES
	('BBG_PLAYER_HAS_MOBILISATION_REQUIREMENTS' , 'REQUIREMENTSET_TEST_ALL');

INSERT OR IGNORE INTO RequirementSetRequirements(RequirementSetId , RequirementId) VALUES
	('BBG_PLAYER_HAS_MOBILISATION_REQUIREMENTS', 'BBG_PLAYER_HAS_MOBILISATION_REQUIREMENT');

INSERT OR IGNORE INTO Requirements(RequirementId , RequirementType) VALUES
	('BBG_PLAYER_HAS_MOBILISATION_REQUIREMENT' , 'REQUIREMENT_PLAYER_HAS_CIVIC');

INSERT OR IGNORE INTO RequirementArguments(RequirementId , Name, Value) VALUES
	('BBG_PLAYER_HAS_MOBILISATION_REQUIREMENT' , 'CivicType', 'CIVIC_MOBILIZATION');