

-- Grand Bazaar buff
UPDATE Building_GreatPersonPoints SET PointsPerTurn=2 WHERE BuildingType='BUILDING_GRAND_BAZAAR';
INSERT INTO Modifiers(ModifierId, ModifierType, RunOnce, Permanent) VALUES
    ('BBG_GRAND_BAZAAR_GOV_POINT', 'MODIFIER_ALL_PLAYERS_ADJUST_GOVERNOR_POINTS', 1, 1);
INSERT INTO ModifierArguments(ModifierId, Name, Value) VALUES
    ('BBG_GRAND_BAZAAR_GOV_POINT', 'Delta', '1');
INSERT INTO BuildingModifiers(BuildingType, ModifierId) VALUES
    ('BUILDING_GRAND_BAZAAR', 'BBG_BANK_TRADEROUTE_FROM_DOMESTIC'),
    ('BUILDING_GRAND_BAZAAR', 'BBG_BANK_TRADEROUTE_TO_DOMESTIC'),
    ('BUILDING_GRAND_BAZAAR', 'BBG_BANK_TRADEROUTE_FROM_INTERNATIONAL'),
    ('BUILDING_GRAND_BAZAAR', 'BBG_BANK_TRADEROUTE_TO_INTERNATIONAL'),
    ('BUILDING_GRAND_BAZAAR', 'BBG_GRAND_BAZAAR_GOV_POINT');