
-- 23/04/2021 iElden: Implemented by Firaxis
--DELETE FROM ModifierArguments WHERE ModifierId='TRAIT_CULTURE_FROM_INTERNATIONAL_TRADE_ROUTES';
--INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
--    ('TRAIT_CULTURE_FROM_INTERNATIONAL_TRADE_ROUTES', 'YieldType', 'YIELD_CULTURE'),
--    ('TRAIT_CULTURE_FROM_INTERNATIONAL_TRADE_ROUTES', 'Amount', 2);
--
--DELETE FROM ModifierArguments WHERE ModifierId='TRAIT_CULTURE_FROM_INCOMING_TRADE_ROUTES';
--INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
--    ('TRAIT_CULTURE_FROM_INCOMING_TRADE_ROUTES', 'YieldType', 'YIELD_CULTURE'),
--    ('TRAIT_CULTURE_FROM_INCOMING_TRADE_ROUTES', 'Amount', 2);

UPDATE StartBiasRivers SET Tier=3 WHERE CivilizationType='CIVILIZATION_NETHERLANDS';
UPDATE StartBiasTerrains SET Tier=5 WHERE CivilizationType='CIVILIZATION_NETHERLANDS' AND TerrainType='TERRAIN_COAST';