-- by: iElden

INSERT INTO Modifiers(ModifierId, ModifierType) VALUES
    ('BBG_TRADE_TREATY_DOMESTIC_TRADE_ROUTE_DISABLED', 'MODIFIER_PLAYER_TRADE_ROUTES_DISABLE'),
    ('BBG_TRADE_TREATY_DOMESTIC_TRADE_ROUTE_GOLD', 'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_YIELD_FOR_DOMESTIC');

INSERT INTO ModifierArguments(ModifierId, Name, Value) VALUES
    ('BBG_TRADE_TREATY_DOMESTIC_TRADE_ROUTE_DISABLED', 'InternationalMinors', '0'),
    ('BBG_TRADE_TREATY_DOMESTIC_TRADE_ROUTE_DISABLED', 'InternationalMajors', '0'),
    ('BBG_TRADE_TREATY_DOMESTIC_TRADE_ROUTE_DISABLED', 'Domestic', '1'),
    ('BBG_TRADE_TREATY_DOMESTIC_TRADE_ROUTE_GOLD', 'YieldType', 'YIELD_GOLD'),
    ('BBG_TRADE_TREATY_DOMESTIC_TRADE_ROUTE_GOLD', 'Amount', '4'),
    ('BBG_TRADE_TREATY_DOMESTIC_TRADE_ROUTE_GOLD', 'Intercontinental', '0');

INSERT INTO ResolutionEffects(ResolutionEffectId, ResolutionType, WhichEffect, ModifierId) VALUES
    (23, 'WC_RES_TRADE_TREATY', 2, 'BBG_TRADE_TREATY_DOMESTIC_TRADE_ROUTE_DISABLED'),
    (28, 'WC_RES_TRADE_TREATY', 2, 'BBG_TRADE_TREATY_DOMESTIC_TRADE_ROUTE_GOLD');