------------------------------------------------------------------------------
--	FILE:	 new_bbg_religion.sql
--	AUTHOR:  iElden, D. / Jack The Narrator
--	PURPOSE: Database modifications by new BBG
------------------------------------------------------------------------------
--==============================================================================================
--******				R E L I G I O N					  ******
--==============================================================================================
/*
-- Distance for religion spread, base game is 10
--UPDATE GlobalParameters SET Value='20' WHERE Name='RELIGION_SPREAD_ADJACENT_CITY_DISTANCE';

-- Strength for religion spread, base game is 1
--UPDATE GlobalParameters SET Value='1' WHERE Name='RELIGION_SPREAD_ADJACENT_PER_TURN_PRESSURE';

-- Adjust Itinerant preachers base game is 30% so 3 for 10, hence changing from 6 for 20 to maintain 30% ratio
--UPDATE ModifierArguments SET Value='3' WHERE ModifierId='ITINERANT_PREACHERS_SPREAD_DISTANCE';

-- This is to increase the Strength of the pressure base on the civic tree
INSERT OR IGNORE INTO Types 
	(Type, Kind)
	VALUES
	('MODIFIER_ALL_CITIES_RELIGION_PRESSURE', 'KIND_MODIFIER');

INSERT OR IGNORE INTO DynamicModifiers 
	(ModifierType, CollectionType, EffectType)
	VALUES
	('MODIFIER_ALL_CITIES_RELIGION_PRESSURE', 'COLLECTION_PLAYER_CITIES', 'EFFECT_ADJUST_CITY_RELIGION_PRESSURE');

INSERT OR IGNORE INTO Modifiers 
	(ModifierId, ModifierType)
	VALUES
	('MODIIFIER_DECREASE_75_RELIGIOUS_PRESSURE', 'MODIFIER_ALL_CITIES_RELIGION_PRESSURE'),
	('MODIIFIER_ADD_25_RELIGIOUS_PRESSURE', 'MODIFIER_ALL_CITIES_RELIGION_PRESSURE'),
	('MODIIFIER_ADD_50_RELIGIOUS_PRESSURE', 'MODIFIER_ALL_CITIES_RELIGION_PRESSURE'),
	('MODIIFIER_ADD_100_RELIGIOUS_PRESSURE', 'MODIFIER_ALL_CITIES_RELIGION_PRESSURE');

INSERT OR IGNORE INTO ModifierArguments 
	(ModifierId, Name, Value)
	VALUES
	('MODIIFIER_DECREASE_75_RELIGIOUS_PRESSURE', 'Amount','-75'),
	('MODIIFIER_ADD_25_RELIGIOUS_PRESSURE', 'Amount', '25'),
	('MODIIFIER_ADD_50_RELIGIOUS_PRESSURE', 'Amount', '50'),
	('MODIIFIER_ADD_100_RELIGIOUS_PRESSURE', 'Amount', '100');

--INSERT OR IGNORE INTO CivicModifiers 
--	(CivicType , ModifierId)
--	VALUES
--	('CIVIC_CODE_OF_LAWS','MODIIFIER_DECREASE_75_RELIGIOUS_PRESSURE'),
--	('CIVIC_MYSTICISM','MODIIFIER_ADD_25_RELIGIOUS_PRESSURE'),
--	('CIVIC_THEOLOGY','MODIIFIER_ADD_50_RELIGIOUS_PRESSURE'),
--	('CIVIC_REFORMED_CHURCH','MODIIFIER_ADD_50_RELIGIOUS_PRESSURE');
*/	



-- Delete Dance of Aurora Beliefs adjancency on Hills
DELETE FROM BeliefModifiers WHERE BeliefType='BELIEF_DANCE_OF_THE_AURORA' AND ModifierId='DANCE_OF_THE_AURORA_FAITHTUNDRAHILLSADJACENCY';

/*
-- Dance of Aurora Give +3 faith on city center on Tundra tiles in city with HS
INSERT INTO BeliefModifiers
		(BeliefType,									ModifierId)
VALUES	('BELIEF_DANCE_OF_THE_AURORA', 			'DANCE_OF_THE_AURORA_FAITH_TUNDRA_HILLS');
/*
		('BELIEF_DANCE_OF_THE_AURORA', 			'DANCE_OF_THE_AURORA_FAITH_TUNDRA'),
		('BELIEF_DANCE_OF_THE_AURORA', 			'DANCE_OF_THE_AURORA_FAITH_SNOW_HILLS'),
		('BELIEF_DANCE_OF_THE_AURORA', 			'DANCE_OF_THE_AURORA_FAITH_SNOW');
*/
/*
INSERT INTO DistrictModifiers
		(DistrictType,									ModifierId)
VALUES	('DISTRICT_HOLY_SITE', 							'DANCE_OF_THE_AURORA_FAITH_TUNDRA_HILLS');


INSERT INTO Modifiers
		(ModifierId,										ModifierType,											SubjectRequirementSetId)
VALUES	('DANCE_OF_THE_AURORA_FAITH_TUNDRA_HILLS',			'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',					'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
		('DANCE_OF_THE_AURORA_FAITH_TUNDRA_HILLS_MODIFIER',	'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_CHANGE',		'DISTRICT_IS_HOLY_SITE_ON_TUNDRA');
		
INSERT INTO ModifierArguments
		(ModifierId,										Name,							Value)
VALUES	('DANCE_OF_THE_AURORA_FAITH_TUNDRA_HILLS',			'ModifierId',					'DANCE_OF_THE_AURORA_FAITH_TUNDRA_HILLS_MODIFIER'),
		('DANCE_OF_THE_AURORA_FAITH_TUNDRA_HILLS_MODIFIER',	'YieldType',					'YIELD_FAITH'),
		('DANCE_OF_THE_AURORA_FAITH_TUNDRA_HILLS_MODIFIER',	'Amount',						3);

INSERT INTO RequirementSets
		(RequirementSetId,															RequirementSetType)
VALUES	('DISTRICT_IS_HOLY_SITE_ON_TUNDRA',											'REQUIREMENTSET_TEST_ALL');			

INSERT INTO RequirementSetRequirements
		(RequirementSetId,													RequirementId)
VALUES	('DISTRICT_IS_HOLY_SITE_ON_TUNDRA',									'REQUIRES_DISTRICT_IS_HOLY_SITE');

INSERT INTO Requirements
		(RequirementId, 										RequirementType)
VALUES	('REQUIRES_DISTRICT_IS_HOLY_SITE', 						'REQUIREMENT_DISTRICT_TYPE_MATCHES');			

INSERT INTO RequirementArguments
		(RequirementId, 							Name,						Value)
VALUES	('REQUIRES_DISTRICT_IS_HOLY_SITE', 			'DistrictType', 			'DISTRICT_HOLY_SITE');	


	
		
/*
		('DANCE_OF_THE_AURORA_FAITH_TUNDRA',				'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',					NULL),
		('DANCE_OF_THE_AURORA_FAITH_SNOW',					'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',					NULL),
		('DANCE_OF_THE_AURORA_FAITH_SNOW_HILLS',			'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',					'DANCE_OF_THE_AURORA_FAITH_SNOW_REQUIREMENTS');
		
		
	/*
	VALUES	('DANCE_OF_THE_AURORA_FAITH_TUNDRA_HILLS',			'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',					'DANCE_OF_THE_AURORA_FAITH_TUNDRA_HILLS_REQUIREMENTS'),
		('DANCE_OF_THE_AURORA_FAITH_TUNDRA',				'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',					'DANCE_OF_THE_AURORA_FAITH_TUNDRA_REQUIREMENTS'),
		('DANCE_OF_THE_AURORA_FAITH_SNOW',					'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',					'DANCE_OF_THE_AURORA_FAITH_SNOW_HILLS_REQUIREMENTS'),
		('DANCE_OF_THE_AURORA_FAITH_SNOW_HILLS',			'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',					'DANCE_OF_THE_AURORA_FAITH_SNOW_REQUIREMENTS');
	*/
	/*
INSERT INTO ModifierArguments
		(ModifierId,										Name,							Value)
VALUES	('DANCE_OF_THE_AURORA_FAITH_SNOW',					'YieldType',					'YIELD_FAITH'),
		('DANCE_OF_THE_AURORA_FAITH_SNOW',					'Amount',						3),
		('DANCE_OF_THE_AURORA_FAITH_SNOW_HILLS',			'YieldType',					'YIELD_FAITH'),
		('DANCE_OF_THE_AURORA_FAITH_SNOW_HILLS',			'Amount',						3),
		('DANCE_OF_THE_AURORA_FAITH_TUNDRA',				'YieldType',					'YIELD_FAITH'),
		('DANCE_OF_THE_AURORA_FAITH_TUNDRA',				'Amount',						3),
		('DANCE_OF_THE_AURORA_FAITH_TUNDRA_HILLS',			'YieldType',					'YIELD_FAITH'),
		('DANCE_OF_THE_AURORA_FAITH_TUNDRA_HILLS',			'Amount',						3);

INSERT INTO RequirementSets
		(RequirementSetId,										RequirementSetType)
VALUES	('DANCE_OF_THE_AURORA_FAITH_SNOW_REQUIREMENTS',	'REQUIREMENTSET_TEST_ALL');

INSERT INTO RequirementSetRequirements
		(RequirementSetId,										RequirementId)
VALUES	('DANCE_OF_THE_AURORA_FAITH_SNOW_REQUIREMENTS',	'REQUIRES_PLOT_IS_SNOW_HILLS');

INSERT INTO Requirements
		(RequirementId, 										RequirementType)
VALUES	('REQUIRES_PLOT_IS_SNOW_HILLS',						'REQUIREMENT_TERRAIN_TYPE_MATCHES');

INSERT INTO RequirementArguments
		(RequirementId, 							Name,						Value)
VALUES	('REQUIRES_PLOT_IS_SNOW_HILLS', 			'TerrainType', 				'TERRAIN_SNOW_HILLS');

/*	
INSERT INTO Requirements
		(RequirementId, 										RequirementType)
VALUES	('REQUIRES_CITY_HAS_HOLY_SITE',							'REQUIREMENT_CITY_HAS_DISTRICT');


		('REQUIRES_PLOT_IS_TUNDRA_HILLS', 						'REQUIREMENT_PLOT_TERRAIN_TYPE_MATCHES'),
		('REQUIRES_PLOT_IS_TUNDRA', 							'REQUIREMENT_PLOT_TERRAIN_TYPE_MATCHES'),	
		('REQUIRES_PLOT_IS_SNOW_HILLS', 						'REQUIREMENT_PLOT_TERRAIN_TYPE_MATCHES'),
		('REQUIRES_PLOT_IS_SNOW', 								'REQUIREMENT_PLOT_TERRAIN_TYPE_MATCHES');			

INSERT INTO RequirementArguments
		(RequirementId, 							Name,						Value)
VALUES	('REQUIRES_CITY_HAS_HOLY_SITE', 			'DistrictType',				'DISTRICT_HOLY_SITE');

		('REQUIRES_PLOT_IS_TUNDRA_HILLS', 			'TerrainType', 				'TERRAIN_TUNDRA_HILLS'),
		('REQUIRES_PLOT_IS_TUNDRA', 				'TerrainType', 				'TERRAIN_TUNDRA'),	
		('REQUIRES_PLOT_IS_SNOW_HILLS', 			'TerrainType', 				'TERRAIN_SNOW_HILLS'),
		('REQUIRES_PLOT_IS_SNOW', 					'TerrainType', 				'TERRAIN_SNOW');	



INSERT INTO RequirementSets
		(RequirementSetId,										RequirementSetType)
VALUES	('DANCE_OF_THE_AURORA_FAITH_SNOW_REQUIREMENTS',			'REQUIREMENTSET_TEST_ALL'),
		('DANCE_OF_THE_AURORA_FAITH_SNOW_HILLS_REQUIREMENTS',	'REQUIREMENTSET_TEST_ALL'),
		('DANCE_OF_THE_AURORA_FAITH_TUNDRA_HILLS_REQUIREMENTS',	'REQUIREMENTSET_TEST_ALL'),
		('DANCE_OF_THE_AURORA_FAITH_TUNDRA_REQUIREMENTS',		'REQUIREMENTSET_TEST_ALL');

INSERT INTO RequirementSetRequirements
		(RequirementSetId,										RequirementId)
VALUES	('DANCE_OF_THE_AURORA_FAITH_SNOW_REQUIREMENTS',			'REQUIRES_DISTRICT_IS_CITY_CENTER'),
--		('DANCE_OF_THE_AURORA_FAITH_SNOW_REQUIREMENTS',			'REQUIRES_PLOT_IS_SNOW'),
		('DANCE_OF_THE_AURORA_FAITH_SNOW_REQUIREMENTS',			'REQUIRES_CITY_HAS_HOLY_SITE');
		
		('DANCE_OF_THE_AURORA_FAITH_TUNDRA_HILLS_REQUIREMENTS',	'REQUIRES_DISTRICT_IS_CITY_CENTER'),
--		('DANCE_OF_THE_AURORA_FAITH_TUNDRA_HILLS_REQUIREMENTS',	'REQUIRES_PLOT_IS_TUNDRA_HILLS'),
		('DANCE_OF_THE_AURORA_FAITH_TUNDRA_HILLS_REQUIREMENTS',	'REQUIRES_CITY_HAS_HOLY_SITE'),
		
		('DANCE_OF_THE_AURORA_FAITH_TUNDRA_REQUIREMENTS',		'REQUIRES_DISTRICT_IS_CITY_CENTER'),
--		('DANCE_OF_THE_AURORA_FAITH_TUNDRA_REQUIREMENTS',		'REQUIRES_PLOT_IS_TUNDRA'),
		('DANCE_OF_THE_AURORA_FAITH_TUNDRA_REQUIREMENTS',		'REQUIRES_CITY_HAS_HOLY_SITE'),
		
		('DANCE_OF_THE_AURORA_FAITH_SNOW_HILLS_REQUIREMENTS',	'REQUIRES_DISTRICT_IS_CITY_CENTER'),
--		('DANCE_OF_THE_AURORA_FAITH_SNOW_HILLS_REQUIREMENTS',	'REQUIRES_PLOT_IS_SNOW_HILLS'),
		('DANCE_OF_THE_AURORA_FAITH_SNOW_HILLS_REQUIREMENTS',	'REQUIRES_CITY_HAS_HOLY_SITE');

