-- Babylon Pack - Great Writer

-- Babylon Pack - Great Artist
UPDATE GreatWork_YieldChanges SET YieldChange=4 WHERE GreatWorkType='GREATWORK_BEHZAD_1';
UPDATE GreatWork_YieldChanges SET YieldChange=4 WHERE GreatWorkType='GREATWORK_BEHZAD_1';
UPDATE GreatWork_YieldChanges SET YieldChange=4 WHERE GreatWorkType='GREATWORK_BEHZAD_2';
UPDATE GreatWork_YieldChanges SET YieldChange=4 WHERE GreatWorkType='GREATWORK_TOHAKU_1';
UPDATE GreatWork_YieldChanges SET YieldChange=4 WHERE GreatWorkType='GREATWORK_TOHAKU_2';
UPDATE GreatWork_YieldChanges SET YieldChange=4 WHERE GreatWorkType='GREATWORK_TOHAKU_3';
UPDATE GreatWork_YieldChanges SET YieldChange=4 WHERE GreatWorkType='GREATWORK_KANDINSKY_1';
UPDATE GreatWork_YieldChanges SET YieldChange=4 WHERE GreatWorkType='GREATWORK_KANDINSKY_2';
UPDATE GreatWork_YieldChanges SET YieldChange=4 WHERE GreatWorkType='GREATWORK_KANDINSKY_3';
-- Babylon Pack - Great Musician
UPDATE GreatWork_YieldChanges SET YieldChange=12 WHERE GreatWorkType='GREATWORK_BABYLON_CANTEMIR_1';
UPDATE GreatWork_YieldChanges SET YieldChange=12 WHERE GreatWorkType='GREATWORK_BABYLON_CANTEMIR_2';
UPDATE GreatWork_YieldChanges SET YieldChange=12 WHERE GreatWorkType='GREATWORK_BABYLON_CANTEMIR_3';
UPDATE GreatWork_YieldChanges SET YieldChange=12 WHERE GreatWorkType='GREATWORK_BABYLON_JOPLIN_1';
UPDATE GreatWork_YieldChanges SET YieldChange=12 WHERE GreatWorkType='GREATWORK_BABYLON_JOPLIN_2';
UPDATE GreatWork_YieldChanges SET YieldChange=12 WHERE GreatWorkType='GREATWORK_BABYLON_JOPLIN_3';
