-- diggers require niter 
UPDATE Units SET StrategicResource='RESOURCE_NITER' WHERE UnitType='UNIT_DIGGER';
-- diggers are niter maint 1
INSERT OR IGNORE INTO Units_XP2 (UnitType , ResourceCost  , ResourceMaintenanceAmount , ResourceMaintenanceType)
	VALUES ('UNIT_DIGGER' , 1 , 1 , 'RESOURCE_NITER');
-- liberation bonus reduced to +50%
INSERT OR IGNORE INTO ModifierArguments (ModifierId, Name, Value)
	VALUES
	('TRAIT_CITADELCIVILIZATION_LIBERATION_PRODUCTION_XP2', 'YieldType', 'YIELD_PRODUCTION'),
	('TRAIT_CITADELCIVILIZATION_LIBERATION_PRODUCTION_XP2', 'Amount', '50');

-- cattle +1 prod
INSERT OR IGNORE INTO Requirements (RequirementId, RequirementType)
VALUES ('REQUIRES_PLOT_HAS_CATTLE', 'REQUIREMENT_PLOT_RESOURCE_TYPE_MATCHES');
INSERT OR IGNORE INTO RequirementArguments (RequirementId, Name, Value)
VALUES ('REQUIRES_PLOT_HAS_CATTLE', 'ResourceType', 'RESOURCE_CATTLE');
INSERT OR IGNORE INTO RequirementSets (RequirementSetId, RequirementSetType)
VALUES ('LAND_DOWN_UNDER_CATTLE_PROD_REQUIREMENTS', 'REQUIREMENTSET_TEST_ALL');
INSERT OR IGNORE INTO RequirementSetRequirements(RequirementSetId, RequirementId)
VALUES ('LAND_DOWN_UNDER_CATTLE_PROD_REQUIREMENTS', 'REQUIRES_PLOT_HAS_CATTLE');
INSERT OR IGNORE INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId, SubjectStackLimit)
VALUES ('LAND_DOWN_UNDER_CATTLE_PROD', 'MODIFIER_PLAYER_ADJUST_PLOT_YIELD', 'LAND_DOWN_UNDER_CATTLE_PROD_REQUIREMENTS',  NULL);
INSERT OR IGNORE INTO ModifierArguments (ModifierId, Name, Value)
VALUES ('LAND_DOWN_UNDER_CATTLE_PROD', 'YieldType', 'YIELD_PRODUCTION'),
       ('LAND_DOWN_UNDER_CATTLE_PROD', 'Amount', 1);
INSERT OR IGNORE INTO TraitModifiers (TraitType, ModifierId)
VALUES ('TRAIT_CIVILIZATION_LAND_DOWN_UNDER', 'LAND_DOWN_UNDER_CATTLE_PROD');

-- pasture +1 culture after political philosophy
INSERT OR IGNORE INTO Requirements (RequirementId, RequirementType)
VALUES ('REQUIRES_PLAYER_HAS_POLITICAL_PHILOSOPHY', 'REQUIREMENT_PLAYER_HAS_CIVIC');
INSERT OR IGNORE INTO RequirementArguments (RequirementId , Name, Value)
VALUES ('REQUIRES_PLAYER_HAS_POLITICAL_PHILOSOPHY', 'CivicType', 'CIVIC_POLITICAL_PHILOSOPHY');
INSERT OR IGNORE INTO RequirementSets (RequirementSetId, RequirementSetType)
VALUES ('LAND_DOWN_UNDER_PASTURE_CULTURE_REQUIREMENTS', 'REQUIREMENTSET_TEST_ALL');
INSERT OR IGNORE INTO RequirementSetRequirements(RequirementSetId, RequirementId)
VALUES ('LAND_DOWN_UNDER_PASTURE_CULTURE_REQUIREMENTS', 'REQUIRES_PLOT_HAS_PASTURE');
INSERT OR IGNORE INTO RequirementSetRequirements(RequirementSetId , RequirementId)
VALUES ('LAND_DOWN_UNDER_PASTURE_CULTURE_REQUIREMENTS', 'REQUIRES_PLAYER_HAS_POLITICAL_PHILOSOPHY');  
INSERT OR IGNORE INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId, SubjectStackLimit)
VALUES ('LAND_DOWN_UNDER_PASTURE_CULTURE', 'MODIFIER_PLAYER_ADJUST_PLOT_YIELD', 'LAND_DOWN_UNDER_PASTURE_CULTURE_REQUIREMENTS',  NULL);
INSERT OR IGNORE INTO ModifierArguments (ModifierId, Name, Value)
VALUES ('LAND_DOWN_UNDER_PASTURE_CULTURE', 'YieldType', 'YIELD_CULTURE'),
       ('LAND_DOWN_UNDER_PASTURE_CULTURE', 'Amount', 1);
INSERT OR IGNORE INTO TraitModifiers (TraitType, ModifierId)
VALUES ('TRAIT_CIVILIZATION_LAND_DOWN_UNDER', 'LAND_DOWN_UNDER_PASTURE_CULTURE');

-- outback stations +1 appeal to surrounding tiles
UPDATE Improvements SET Appeal = 1 WHERE ImprovementType = 'IMPROVEMENT_OUTBACK_STATION';

-- Australia reduce production on liberation for gathering storm
UPDATE ModifierArguments SET Value='50' WHERE ModifierId='TRAIT_CITADELCIVILIZATION_LIBERATION_PRODUCTION_XP2' and Name='Amount';
UPDATE ModifierArguments SET Value='10' WHERE ModifierId='TRAIT_CITADELCIVILIZATION_LIBERATION_PRODUCTION_XP2' and Name='TurnsActive';